name: birdle
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  legal_wordle_words:
    git: https://github.com/ericwindmill/legal_wordle_words
  russian_wordle_repo:
    git: https://github.com/syferever/russian_wordle_repo

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
